### ISSUE TITLE
Unable to safely access requestBody

### ISSUE THREAD

**Issue by msabree** [freaktechnik/jetpack-requestmod#1]
My first choice was to use the WebRequest.jsm but requestBody access is not currently supported. See here: https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/WebRequest.jsm#Chrome_incompatibilities

So I attempted to use this module but accessing the requestBody causes errors to be thrown and the network request to get aborted. I was able to log the request data but the request itself fails. See fiddle here: https://jsfiddle.net/sx43t15j/

I saw in the documentation that the requestObject may get destroyed before the processContent callback is called... Is that what is happening here? If so, any thoughts on how this can be resolved. If you point me in the right direction I wouldn't mind taking a look at the code and doing a pull request. If I have an error in my JavaScript please advise.

Best,

Makeen

**Comment by freaktechnik** [comment]
You're not supposed to set the new content inside the `processContent` callback, instead you just return it.

**Comment by msabree** [comment]
I found the issue. Your edit2 was what I had originally and I was still noticing the requests failing. After some research I found that you have to save the requestMethod when the stream is first accessed and set it after you call channel.setUploadStream. channel.setUploadStream changes the requestMethod from POST to PUT causing requests to fail server-side. Adding this change resolved my main issue. See here: http://forums.mozillazine.org/viewtopic.php?f=19&p=10383983

Notice the comment: // order important - setUploadStream resets to PUT

Hopefully this helps others.

Best,

Makeen

**Comment by freaktechnik** [comment]
Thanks, I've commented directly into your commit.

**Comment by freaktechnik** [comment]
I hope to have fixed most of this with 8df3bbec866c6f8c72b3df8e01c8ff0b91472d7e. If you can think of something that was an issue for you that I am not testing  yet, I'd like to add that as a unit test too.

**Comment by msabree** [comment]
Awesome! Content type and request method integrity was all that I noticed. I'll close this bug and begin testing the new package as soon as it's ready.

**Comment by freaktechnik** [comment]
Hm, I'm actually not sure if using the distinct method for the x-www-form-urlencoded is useful, since the actual encoded data string that you'd set the content to doesn't contain it, afaik.

**Comment by msabree** [comment]
The issue i was seeing with url encoded streams may have been a side effect of this.type not having the correct contenttype value set. So checking for that specific type may not be necessary.
